import { ProjectDataTable } from '../components/Table/TableTypes/typesAPI'

const projectDataTableLeadAPI: ProjectDataTable = [
  {
    projectName: { name: 'AC Reporter', billable: true },
    tag: ['Guru', 'Page Mockup'],
    team: [
      'Nadezhda Lazurenko',
      'Kent Peacock',
      'Nick Johnson',
      'Kate Churikova',
      'Kate Middleton',
      'Nick Johnson',
      'Kate Churikova',
    ],
    manager: ['Alexandr Kurilov'],
    categorie: ['CMS Production'],
    basicEstimation: 324.94,
    timeSpentByPeriod: 5.5,
    efficiencyByPeriod: '100%',
  },
  {
    projectName: { name: 'Search Sumo', billable: false },
    tag: ['Page Mockup'],
    team: ['Kate Lazurenko'],
    manager: ['Alexandr Kurilov'],
    categorie: ['NIX Internal'],
    basicEstimation: 32.0,
    timeSpentByPeriod: 15.0,
    efficiencyByPeriod: '45%',
  },
  {
    projectName: { name: 'Artifacts (Blockchain for research)', billable: true },
    tag: ['Guru', 'Page Mockup'],
    team: [
      'Nadezhda Lazurenko',
      'Kent Peacock',
      'Nick Johnson',
      'Kate Churikova',
      'Kate Middleton',
    ],
    manager: ['Alexandr Kurilov'],
    categorie: ['CMS Production'],
    basicEstimation: 324.94,
    timeSpentByPeriod: 5.5,
    efficiencyByPeriod: '88%',
  },
  {
    projectName: { name: 'Walker Enter', billable: false },
    tag: ['Page Mockup'],
    team: ['Kate Middleton'],
    manager: ['Alexandr Kurilov'],
    categorie: ['NIX Internal'],
    basicEstimation: 32.0,
    timeSpentByPeriod: 15.0,
    efficiencyByPeriod: '100%',
  },
  {
    projectName: { name: 'AC Reporter (NIX’s System)', billable: true },
    tag: ['Guru', 'Page Mockup'],
    team: ['Nadezhda Lazurenko', 'Kent Peacock'],
    manager: ['Alexandr Kurilov'],
    categorie: ['CMS Production'],
    basicEstimation: 324.94,
    timeSpentByPeriod: 5.5,
    efficiencyByPeriod: '100%',
  },
  {
    projectName: { name: 'Search Sumo', billable: false },
    tag: ['Page Mockup'],
    team: ['Kate Lazurenko'],
    manager: ['Alexandr Kurilov'],
    categorie: ['NIX Internal'],
    basicEstimation: 32.0,
    timeSpentByPeriod: 15.0,
    efficiencyByPeriod: '90%',
  },
  {
    projectName: { name: 'Artifacts (Blockchain for research)', billable: true },
    tag: ['Guru', 'Page Mockup'],
    team: [
      'Nadezhda Lazurenko',
      'Kent Peacock',
      'Nick Johnson',
      'Kate Churikova',
      'Kate Middleton',
      'Nick Johnson',
      'Kate Churikova',
    ],
    manager: ['Alexandr Kurilov'],
    categorie: ['CMS Production'],
    basicEstimation: 324.94,
    timeSpentByPeriod: 5.5,
    efficiencyByPeriod: '100%',
  },
  {
    projectName: { name: 'Walker Enter', billable: false },
    tag: ['Page Mockup'],
    team: ['Kate Lazurenko'],
    manager: ['Alexandr Kurilov'],
    categorie: ['NIX Internal'],
    basicEstimation: 32.0,
    timeSpentByPeriod: 15.0,
    efficiencyByPeriod: '78%',
  },
  {
    projectName: { name: 'AC Reporter', billable: false },
    tag: ['Guru', 'Page Mockup'],
    team: [
      'Nadezhda Lazurenko',
      'Kent Peacock',
      'Nick Johnson',
      'Kate Churikova',
      'Kate Middleton',
      'Nick Johnson',
      'Kate Churikova',
    ],
    manager: ['Alexandr Kurilov'],
    categorie: ['CMS Production'],
    basicEstimation: 324.94,
    timeSpentByPeriod: 5.5,
    efficiencyByPeriod: '100%',
  },
  {
    projectName: { name: 'Search Sumo', billable: false },
    tag: ['Page Mockup'],
    team: ['Kate Lazurenko'],
    manager: ['Alexandr Kurilov'],
    categorie: ['NIX Internal'],
    basicEstimation: 32.0,
    timeSpentByPeriod: 15.0,
    efficiencyByPeriod: '100%',
  },
]
const projectDataTableDevAPI: ProjectDataTable = [
  {
    projectName: { name: 'AC Reporter', billable: true },
    team: [
      'Nadezhda Lazurenko',
      'Kent Peacock',
      'Nick Johnson',
      'Kate Churikova',
      'Kate Middleton',
      'Nick Johnson',
      'Kate Churikova',
    ],
    manager: ['Alexandr Kurilov'],
    categorie: ['CMS Production'],
    basicEstimation: 324.94,
    timeSpentByPeriod: 5.5,
    efficiencyByPeriod: '100%',
  },
  {
    projectName: { name: 'Search Sumo', billable: false },
    team: ['Kate Lazurenko'],
    manager: ['Alexandr Kurilov'],
    categorie: ['NIX Internal'],
    basicEstimation: 32.0,
    timeSpentByPeriod: 15.0,
    efficiencyByPeriod: '45%',
  },
  {
    projectName: {
      name: 'Artifacts (Blockchain for research, research and research)',
      billable: true,
    },
    team: [
      'Nadezhda Lazurenko',
      'Kent Peacock',
      'Nick Johnson',
      'Kate Churikova',
      'Kate Middleton',
    ],
    manager: ['Alexandr Kurilov'],
    categorie: ['CMS Production'],
    basicEstimation: 324.94,
    timeSpentByPeriod: 5.5,
    efficiencyByPeriod: '88%',
  },
  {
    projectName: { name: 'Walker Enter', billable: false },
    team: ['Kate Middleton'],
    manager: ['Alexandr Kurilov'],
    categorie: ['NIX Internal'],
    basicEstimation: 32.0,
    timeSpentByPeriod: 15.0,
    efficiencyByPeriod: '100%',
  },
  {
    projectName: { name: 'AC Reporter (NIX’s System)', billable: true },
    team: ['Nadezhda Lazurenko', 'Kent Peacock'],
    manager: ['Alexandr Kurilov'],
    categorie: ['CMS Production'],
    basicEstimation: 324.94,
    timeSpentByPeriod: 5.5,
    efficiencyByPeriod: '100%',
  },
  {
    projectName: { name: 'Search Sumo', billable: false },
    team: ['Kate Lazurenko'],
    manager: ['Alexandr Kurilov'],
    categorie: ['NIX Internal'],
    basicEstimation: 32.0,
    timeSpentByPeriod: 15.0,
    efficiencyByPeriod: '90%',
  },
  {
    projectName: {
      name: 'Artifacts (Blockchain for research, research and research)',
      billable: true,
    },
    team: [
      'Nadezhda Lazurenko',
      'Kent Peacock',
      'Nick Johnson',
      'Kate Churikova',
      'Kate Middleton',
      'Nick Johnson',
      'Kate Churikova',
    ],
    manager: ['Alexandr Kurilov'],
    categorie: ['CMS Production'],
    basicEstimation: 324.94,
    timeSpentByPeriod: 5.5,
    efficiencyByPeriod: '100%',
  },
  {
    projectName: { name: 'Walker Enter', billable: false },
    team: ['Kate Lazurenko'],
    manager: ['Alexandr Kurilov'],
    categorie: ['NIX Internal'],
    basicEstimation: 32.0,
    timeSpentByPeriod: 15.0,
    efficiencyByPeriod: '78%',
  },
  {
    projectName: { name: 'AC Reporter', billable: false },
    team: [
      'Nadezhda Lazurenko',
      'Kent Peacock',
      'Nick Johnson',
      'Kate Churikova',
      'Kate Middleton',
      'Nick Johnson',
      'Kate Churikova',
    ],
    manager: ['Alexandr Kurilov'],
    categorie: ['CMS Production'],
    basicEstimation: 324.94,
    timeSpentByPeriod: 5.5,
    efficiencyByPeriod: '100%',
  },
  {
    projectName: { name: 'Search Sumo', billable: false },
    team: ['Kate Lazurenko'],
    manager: ['Alexandr Kurilov'],
    categorie: ['NIX Internal'],
    basicEstimation: 32.0,
    timeSpentByPeriod: 15.0,
    efficiencyByPeriod: '100%',
  },
]

export { projectDataTableLeadAPI, projectDataTableDevAPI }
