import { SimpleTableType } from '../components/DataTable/TableTypes/TableServiceFunctions'

export const categoriesOneDev: SimpleTableType[] = [
  {
    Categories: 'CMS Production (B)',
    'Time (h)': 45.83,
  },
  {
    Categories: 'NIX Internal (B)',
    'Time (h)': 14.5,
  },
  {
    Categories: 'NIX PM’s (B)',
    'Time (h)': 1.0,
  },
  {
    Categories: 'CMS Internal (NB)',
    'Time (h)': 14.5,
  },
  {
    Categories: 'Skill-Up (NB)',
    'Time (h)': 32.0,
  },
  {
    Categories: 'Estimation (NB)',
    'Time (h)': 0,
  },
  {
    Categories: 'Education (NB)',
    'Time (h)': 0,
  },
  {
    Categories: 'Non billable sum',
    'Time (h)': 70.17,
  },
  {
    Categories: 'Billable sum',
    'Time (h)': 70.17,
  },
  {
    Categories: 'Total',
    'Time (h)': 70.17,
  },
]

export const categoriesThreeDevs: SimpleTableType[] = [
  {
    Categories: 'CMS Production (B)',
    'Dianne Russell': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
  },
  {
    Categories: 'NIX Internal (B)',
    'Dianne Russell': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
  },
  {
    Categories: 'NIX PM’s (B)',
    'Dianne Russell': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
  },
  {
    Categories: 'CMS Internal (NB)',
    'Dianne Russell': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
  },
  {
    Categories: 'Skill-Up (NB)',
    'Dianne Russell': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
  },
  {
    Categories: 'Estimation (NB)',
    'Dianne Russell': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
  },
  {
    Categories: 'Education (NB)',
    'Dianne Russell': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
  },
  {
    Categories: 'Non billable sum',
    'Dianne Russell': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
  },
  {
    Categories: 'Billable sum',
    'Dianne Russell': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
  },
  {
    Categories: 'Total',
    'Dianne Russell': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
  },
]

export const categoriesMoreDevs: SimpleTableType[] = [
  {
    Categories: 'CMS Production (B)',
    'All people': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
    'Esther Howaking': 45.83,
    'Cameron Willlins': 45.83,
    'Brooklyn Silmon': 45.83,
    'Leslie Alexander': 45.83,
    'Jenny Wilson': 45.83,
    'Lesly Priston': 45.83,
  },
  {
    Categories: 'NIX Internal (B)',
    'All people': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
    'Esther Howaking': 45.83,
    'Cameron Willlins': 45.83,
    'Brooklyn Silmon': 45.83,
    'Leslie Alexander': 45.83,
    'Jenny Wilson': 45.83,
    'Lesly Priston': 45.83,
  },
  {
    Categories: 'NIX PM’s (B)',
    'All people': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
    'Esther Howaking': 45.83,
    'Cameron Willlins': 45.83,
    'Brooklyn Silmon': 45.83,
    'Leslie Alexander': 45.83,
    'Jenny Wilson': 45.83,
    'Lesly Priston': 45.83,
  },
  {
    Categories: 'CMS Internal (NB)',
    'All people': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
    'Esther Howaking': 45.83,
    'Cameron Willlins': 45.83,
    'Brooklyn Silmon': 45.83,
    'Leslie Alexander': 45.83,
    'Jenny Wilson': 45.83,
    'Lesly Priston': 45.83,
  },
  {
    Categories: 'Skill-Up (NB)',
    'All people': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
    'Esther Howaking': 45.83,
    'Cameron Willlins': 45.83,
    'Brooklyn Silmon': 45.83,
    'Leslie Alexander': 45.83,
    'Jenny Wilson': 45.83,
    'Lesly Priston': 45.83,
  },
  {
    Categories: 'Estimation (NB)',
    'All people': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
    'Esther Howaking': 45.83,
    'Cameron Willlins': 45.83,
    'Brooklyn Silmon': 45.83,
    'Leslie Alexander': 45.83,
    'Jenny Wilson': 45.83,
    'Lesly Priston': 45.83,
  },
  {
    Categories: 'Education (NB)',
    'All people': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
    'Esther Howaking': 45.83,
    'Cameron Willlins': 45.83,
    'Brooklyn Silmon': 45.83,
    'Leslie Alexander': 45.83,
    'Jenny Wilson': 45.83,
    'Lesly Priston': 45.83,
  },
  {
    Categories: 'Non billable sum',
    'All people': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
    'Esther Howaking': 45.83,
    'Cameron Willlins': 45.83,
    'Brooklyn Silmon': 45.83,
    'Leslie Alexander': 45.83,
    'Jenny Wilson': 45.83,
    'Lesly Priston': 45.83,
  },
  {
    Categories: 'Billable sum',
    'All people': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
    'Esther Howaking': 45.83,
    'Cameron Willlins': 45.83,
    'Brooklyn Silmon': 45.83,
    'Leslie Alexander': 45.83,
    'Jenny Wilson': 45.83,
    'Lesly Priston': 45.83,
  },
  {
    Categories: 'Total',
    'All people': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
    'Esther Howaking': 45.83,
    'Cameron Willlins': 45.83,
    'Brooklyn Silmon': 45.83,
    'Leslie Alexander': 45.83,
    'Jenny Wilson': 45.83,
    'Lesly Priston': 45.83,
  },
]
