import { ProjectSingle } from '../components/DataTable/TableTypes/TableServiceFunctions'

export const projectSingleAPI: ProjectSingle[] = [
  {
    taskName: 'Search page mockup',
    developer: [
      'Nadezhda Lazurenko',
      'Kent Peacock',
      'Nick Johnson',
      'Kate Churikova',
      'Kate Middleton',
      'Nick Johnson',
      'Kate Churikova',
      'Nadezhda Lazurenko',
    ],
    workType: ['Programming', 'Meetings', 'Markup', 'Graphic Design', 'Programming WEB'],
    status: 'Completed',
    estimation: 0.0,
    totalTimeSpentByAll: 232.17,
    myTimeSpentByPeriod: 23.0,
    efficiency: '100%',
  },
  {
    taskName: 'Two levels of the menu mockup',
    developer: ['Nadezhda Lazurenko'],
    workType: ['Graphic Design'],
    status: 'Non completed',
    estimation: 0.0,
    totalTimeSpentByAll: 1567.6,
    myTimeSpentByPeriod: 15.0,
    efficiency: null,
  },
  {
    taskName: 'Edit pictures',
    developer: [
      'Nadezhda Lazurenko',
      'Kent Peacock',
      'Nick Johnson',
      'Kate Churikova',
      'Kate Middleton',
      'Nick Johnson',
      'Kate Churikova',
    ],
    workType: ['Graphic Design'],
    status: 'Non completed',
    estimation: 0.0,
    totalTimeSpentByAll: 678.2,
    myTimeSpentByPeriod: 67.0,
    efficiency: null,
  },
  {
    taskName: 'Subdomain home pages mockup',
    developer: ['Nadezhda Lazurenko'],
    workType: ['Graphic Design'],
    status: 'Non completed',
    estimation: 0.0,
    totalTimeSpentByAll: 756.7,
    myTimeSpentByPeriod: 75.0,
    efficiency: null,
  },
  {
    taskName: 'Landing page mockup',
    developer: ['Nadezhda Lazurenko'],
    workType: ['Graphic Design'],
    status: 'Non completed',
    estimation: 0.0,
    totalTimeSpentByAll: 345.6,
    myTimeSpentByPeriod: 45.0,
    efficiency: null,
  },
  {
    taskName: 'Search page mockup',
    developer: [
      'Nadezhda Lazurenko',
      'Kent Peacock',
      'Nick Johnson',
      'Kate Churikova',
      'Kate Middleton',
      'Nick Johnson',
      'Kate Churikova',
      'Nadezhda Lazurenko',
    ],
    workType: ['Programming', 'Meetings', 'Markup', 'Graphic Design', 'Programming WEB'],
    status: 'Completed',
    estimation: 0.0,
    totalTimeSpentByAll: 232.17,
    myTimeSpentByPeriod: 23.0,
    efficiency: '100%',
  },
  {
    taskName: 'Landing page mockup',
    developer: ['Nadezhda Lazurenko', 'Augusta Walter'],
    workType: ['Graphic Design'],
    status: 'Non completed',
    estimation: 0.0,
    totalTimeSpentByAll: 345.6,
    myTimeSpentByPeriod: 45.0,
    efficiency: null,
  },
  {
    taskName: 'Search page mockup',
    developer: ['Nadezhda Lazurenko', 'Kent Peacock'],
    workType: ['Programming', 'Meetings'],
    status: 'Completed',
    estimation: 0.0,
    totalTimeSpentByAll: 232.17,
    myTimeSpentByPeriod: 23.0,
    efficiency: '100%',
  },
  {
    taskName: 'Search page mockup',
    developer: [
      'Nadezhda Lazurenko',
      'Kent Peacock',
      'Nick Johnson',
      'Kate Churikova',
      'Kate Middleton',
    ],
    workType: ['Programming', 'Meetings', 'Markup', 'Graphic Design'],
    status: 'Completed',
    estimation: 0.0,
    totalTimeSpentByAll: 232.17,
    myTimeSpentByPeriod: 23.0,
    efficiency: '100%',
  },
]
