import { SimpleTableType } from '../components/DataTable/TableTypes/TableServiceFunctions'

export const oneDev: SimpleTableType[] = [
  {
    'Job types': 'Programming',
    'Time (h)': 45.83,
  },
  {
    'Job types': 'Markup',
    'Time (h)': 14.5,
  },
  {
    'Job types': 'Graphic Design',
    'Time (h)': 1.0,
  },
  {
    'Job types': 'Estimation',
    'Time (h)': 14.5,
  },
  {
    'Job types': 'Investigation',
    'Time (h)': 32.0,
  },
  {
    'Job types': 'Bug Fixing',
    'Time (h)': 0,
  },
  {
    'Job types': 'Content Writing',
    'Time (h)': 0,
  },
  {
    'Job types': 'Quality Assurance',
    'Time (h)': 70.17,
  },
  {
    'Job types': 'Meetings',
    'Time (h)': 70.17,
  },
  {
    'Job types': 'Other',
    'Time (h)': 70.17,
  },
  {
    'Job types': 'Total',
    'Time (h)': 70.17,
  },
]

export const threeDevs: SimpleTableType[] = [
  {
    'Job types': 'Programming',
    'Dianne Russell': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
  },
  {
    'Job types': 'Markup',
    'Dianne Russell': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
  },
  {
    'Job types': 'Graphic Design',
    'Dianne Russell': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
  },
  {
    'Job types': 'Estimation',
    'Dianne Russell': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
  },
  {
    'Job types': 'Investigation',
    'Dianne Russell': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
  },
  {
    'Job types': 'Bug Fixing',
    'Dianne Russell': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
  },
  {
    'Job types': 'Content Writing',
    'Dianne Russell': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
  },
  {
    'Job types': 'Quality Assurance',
    'Dianne Russell': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
  },
  {
    'Job types': 'Meetings',
    'Dianne Russell': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
  },
  {
    'Job types': 'Other',
    'Dianne Russell': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
  },
  {
    'Job types': 'Total',
    'Dianne Russell': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
  },
]

export const moreDevs: SimpleTableType[] = [
  {
    'Job types': 'Programming',
    'All people': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
    'Esther Howaking': 45.83,
    'Cameron Willlins': 45.83,
    'Brooklyn Silmon': 45.83,
    'Leslie Alexander': 45.83,
    'Jenny Wilson': 45.83,
    'Lesly Priston': 45.83,
  },
  {
    'Job types': 'Markup',
    'All people': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
    'Esther Howaking': 45.83,
    'Cameron Willlins': 45.83,
    'Brooklyn Silmon': 45.83,
    'Leslie Alexander': 45.83,
    'Jenny Wilson': 45.83,
    'Lesly Priston': 45.83,
  },
  {
    'Job types': 'Graphic Design',
    'All people': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
    'Esther Howaking': 45.83,
    'Cameron Willlins': 45.83,
    'Brooklyn Silmon': 45.83,
    'Leslie Alexander': 45.83,
    'Jenny Wilson': 45.83,
    'Lesly Priston': 45.83,
  },
  {
    'Job types': 'Estimation',
    'All people': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
    'Esther Howaking': 45.83,
    'Cameron Willlins': 45.83,
    'Brooklyn Silmon': 45.83,
    'Leslie Alexander': 45.83,
    'Jenny Wilson': 45.83,
    'Lesly Priston': 45.83,
  },
  {
    'Job types': 'Investigation',
    'All people': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
    'Esther Howaking': 45.83,
    'Cameron Willlins': 45.83,
    'Brooklyn Silmon': 45.83,
    'Leslie Alexander': 45.83,
    'Jenny Wilson': 45.83,
    'Lesly Priston': 45.83,
  },
  {
    'Job types': 'Bug Fixing',
    'All people': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
    'Esther Howaking': 45.83,
    'Cameron Willlins': 45.83,
    'Brooklyn Silmon': 45.83,
    'Leslie Alexander': 45.83,
    'Jenny Wilson': 45.83,
    'Lesly Priston': 45.83,
  },
  {
    'Job types': 'Content Writing',
    'All people': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
    'Esther Howaking': 45.83,
    'Cameron Willlins': 45.83,
    'Brooklyn Silmon': 45.83,
    'Leslie Alexander': 45.83,
    'Jenny Wilson': 45.83,
    'Lesly Priston': 45.83,
  },
  {
    'Job types': 'Quality Assurance',
    'All people': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
    'Esther Howaking': 45.83,
    'Cameron Willlins': 45.83,
    'Brooklyn Silmon': 45.83,
    'Leslie Alexander': 45.83,
    'Jenny Wilson': 45.83,
    'Lesly Priston': 45.83,
  },
  {
    'Job types': 'Meetings',
    'All people': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
    'Esther Howaking': 45.83,
    'Cameron Willlins': 45.83,
    'Brooklyn Silmon': 45.83,
    'Leslie Alexander': 45.83,
    'Jenny Wilson': 45.83,
    'Lesly Priston': 45.83,
  },
  {
    'Job types': 'Other',
    'All people': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
    'Esther Howaking': 45.83,
    'Cameron Willlins': 45.83,
    'Brooklyn Silmon': 45.83,
    'Leslie Alexander': 45.83,
    'Jenny Wilson': 45.83,
    'Lesly Priston': 45.83,
  },
  {
    'Job types': 'Total',
    'All people': 45.83,
    'Jane Cooper': 45.83,
    'Wade Warren': 45.83,
    'Esther Howaking': 45.83,
    'Cameron Willlins': 45.83,
    'Brooklyn Silmon': 45.83,
    'Leslie Alexander': 45.83,
    'Jenny Wilson': 45.83,
    'Lesly Priston': 45.83,
  },
]

// export const projectJobOneDev: EmployeeTable[] = [
//   {
//     'Job Types': [
//       'Programming',
//       'Markup',
//       'Graphic Design',
//       'Estimation',
//       'Investigation',
//       'Bug Fixing',
//       'Content Writing',
//       'Quality Assurance',
//       'Meetings',
//       'Other',
//       'Total',
//     ],
//     employees: [
//       {
//         name: 'All people',
//         'Job Types': [
//           {
//             typeName: 'Programming',
//             hours: 45.83,
//           },
//           {
//             typeName: 'Markup',
//             hours: 45.83,
//           },
//           {
//             typeName: 'Graphic Design',
//             hours: 45.83,
//           },
//           {
//             typeName: 'Estimation',
//             hours: 45.83,
//           },
//           {
//             typeName: 'Investigation',
//             hours: 45.83,
//           },
//           {
//             typeName: 'Bug Fixing',
//             hours: 45.83,
//           },
//           {
//             typeName: 'Content Writing',
//             hours: 45.83,
//           },
//           {
//             typeName: 'Quality Assurance',
//             hours: 45.83,
//           },
//           {
//             typeName: 'Meetings',
//             hours: 45.83,
//           },
//           {
//             typeName: 'Other',
//             hours: 45.83,
//           },
//           {
//             typeName: 'Total',
//             hours: 45.83,
//           },
//         ],
//       },
//     ],
//   },
// ]
